Yangjaecheon-Otter-Guardians/simple-thumbnail

- frontend/package-lock.json
- frontend/package.json
- frontend/src/atom/index.tsx
- frontend/src/index.tsx
recoil 설치 및 초기 setting
- index.tsx에서 `App`을 `RecoilRoot`로 감싸줘서 전역상태 적용
|     |        | Recoil로 전역상태 관리 가능|
[참고 레퍼런스](url)
> chore: recoil 설치

- .github/workflows/gh-pages.yml
PR의 개요를 적어주세요
작업 내용을 적어주세요
workflows fix 중입니다
[참고 레퍼런스](url)
> etc : fix workflows

- frontend/package.json
커스텀 도메인 적용에 따른 홈페이지 변경입니다.
작업 내용을 적어주세요
[참고 레퍼런스](url)
> etc : update package.json homepage

- .github/workflows/gh-pages.yml
- frontend/package.json
PR의 개요를 적어주세요
커스텀 도메인 적용에 따른 package.json  homepage 업데이트
작업 내용을 적어주세요
[참고 레퍼런스](url)
> etc : update homepage

- frontend/public/index.html
SEO설정을 해주었습니다.
open graph, twitter, 기본 meta tags 추가
혹시 빼먹은 메타태그가 있다면 알려주세요!!!
[참고 레퍼런스](https://wonism.github.io/meta-for-social/)
> feat : SEO 추가

- frontend/public/index.html
google analytics 설치 작업
index.html에 google analytics script 삽입
[참고 레퍼런스](url)
> etc : set google-analytics script

- frontend/package-lock.json
- frontend/package.json
downloadjs 라이브러리 추가
package.json에 downloadjs라이브러리 추가
> feat : downloadjs 라이브러리 추가

- frontend/src/components/ColorSingle.tsx
- frontend/src/components/ColorUploader.tsx
- frontend/src/components/UnsplashUploader.tsx
검은색 선택 시 흰색 체크 및 배경 변경 추가
검은색 선택 시 흰색 체크 및 배경 변경 추가
[참고 레퍼런스](url)
> 검은색 선택 시 흰색 체크 및 배경 변경 추가

- frontend/src/components/Loading.tsx
> style : img태그 내 alt 변경

- frontend/src/atom/index.tsx
- frontend/src/components/ColorGradation.tsx
- frontend/src/components/ColorSingle.tsx
- frontend/src/components/ColorUploader.tsx
- frontend/src/components/UnsplashUploader.tsx
- frontend/src/sections/Preview.tsx
- 그라데이션 업데이트
- 그라데이션 파트에서 컬러픽커에서 랜덤 그라데이션으로 변경
-  그라데이션으로 인한 콘솔 에러 `backgroundImage`에서 조건부로 해결
- 싱글컬러의 컬러 픽커 선택시 체크 표현
[참고 레퍼런스](url)
> Feature/image 그라데이션 업데이트

- frontend/src/components/common/Dropdown.tsx
- frontend/src/constants/fonts.ts
- frontend/src/sections/TextTool.tsx
드롭다운에서 폰트 확인 가능합니다
드롭다운 공통 컴포넌트 수정 및 드롭다운에 스타일추가
> 드롭다운에서 폰트 확인 가능하도록 수정

- frontend/src/components/ColorSingle.tsx
컬러픽커 닫기 버튼 모양 추가
- 컬러픽커 닫기 버튼 모양 추가
[참고 레퍼런스](url)
> Feature/image 컬러픽커 닫기 버튼 모양 추가

- frontend/src/atom/index.tsx
- frontend/src/sections/Header.tsx
초기화버튼 클릭 시 썸네일 요소가 초기화됩니다.
초기화버튼 클릭 시 reload 추가
(backlog: reload 이외에 recoil상태값들을 초기화하는 방법으로 수정)
> 초기화버튼 동작 추가

- frontend/src/components/common/DivideLine.tsx
divideLine border 픽셀 줄임
divideLine border 픽셀 줄임
[참고 레퍼런스](url)
> style: divideLine border 픽셀 줄임

- frontend/src/components/ColorGradation.tsx
- frontend/src/components/ColorSingle.tsx
- frontend/src/styles/TextItem.module.css
> 색상 버튼 gap 수정

- frontend/src/components/UnsplashUploader.tsx
update unsplash random api loading logic
> fix : unsplash api loading

- frontend/public/index.html
> feature : update description

- frontend/public/index.html
- frontend/src/components/UnsplashUploader.tsx
> 02-27 19:08 업데이트

- frontend/src/components/ImageUploader.tsx
- frontend/src/components/text/TextItem.tsx
- frontend/src/components/text/TextLayoutGroup.tsx
- frontend/src/sections/Preview.tsx
> 미사용 컴포넌트 제거 및 에러 메세지 수정

- frontend/src/sections/Preview.tsx
PR의 개요를 적어주세요
작업 내용을 적어주세요
[참고 레퍼런스](url)
> fix: 프리뷰 다운로드 여백 ref 타겟팅 수정

- frontend/src/components/UnsplashUploader.tsx
PR의 개요를 적어주세요
작업 내용을 적어주세요
[참고 레퍼런스](url)
> fix: 언스플래쉬 리다이렉트 수정

- frontend/src/components/UnsplashUploader.tsx
PR의 개요를 적어주세요
작업 내용을 적어주세요
[참고 레퍼런스](url)
> fix: 언스플래쉬 API 수정

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ImageUploader.tsx
> Feature/image heic적응

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ImageUploader.tsx
- frontend/src/components/UnsplashUploader.tsx
heic 적응
heic 적응
[참고 레퍼런스](url)
> Develop heic 적응

- frontend/src/atom/index.tsx
- frontend/src/components/ColorGradation.tsx
- frontend/src/components/ColorSingle.tsx
- frontend/src/components/ColorUploader.tsx
- frontend/src/components/DownloadButton.tsx
- frontend/src/components/UnsplashUploader.tsx
- frontend/src/features/App.tsx
- frontend/src/sections/BackgroundTool.tsx
- frontend/src/sections/Preview.tsx
- #113 
https://github.com/Yangjaecheon-Otter-Guardians/simple-thumbnail/discussions/108#discussioncomment-5189311
before : 탭을 이동할 때 마다 이전 선택 값이 리셋된다.
after : 선택했던 값이 유지된다.
> fix : fix iOS background img bug

- .github/workflows/gh-pages.yml
- frontend/src/sections/Preview.tsx
- 다운로드 시 모서리가 둥근 버그를 수정하였습니다.
- #129
> 24-02-18 21:15 WEB 1.1 BUG FIX

- frontend/src/components/ColorSingle.tsx
- frontend/src/components/common/Dropdown.tsx
- frontend/src/components/common/Popover.tsx
- 다음 작업을 진행하였습니다
- #139 
작업 내용을 적어주세요
[참고 레퍼런스](url)
> 24-03-03 00:21 WEB 1.3 BUG FIX
